In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
stroke_model = joblib.load(
    r"C:\Users\navee\PreStrokeNet\ML\saved_models\stroke_model.pkl"
)

In [3]:
stroke = pd.read_csv(
    r"C:\Users\navee\PreStrokeNet\Datasets\Processed\stroke_features.csv"
)

In [4]:
keystroke = pd.read_csv(
    r"C:\Users\navee\PreStrokeNet\Datasets\Processed\keystroke_features_final.csv"
)

In [5]:
stroke.head()
keystroke.head()

,Unnamed: 0,H,H.1,H.2,H.3,UD,UD.1,UD.2,UD.3,DD,DD.1,DD.2,DD.3
0,NaN,mean,std,min,max,mean,std,min,max,mean,std,min,max
1,subject,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0.08701730821492953,0.5761039407537828,-0.16712510642753534,0.5601842209595819,-0.9907082116046596,-1.1004065245125598,-0.5773502691896257,-1.0591954890137418,-0.9876101512567117,-1.0991934692759213,-0.47947286960586866,-1.058177039901876
3,1,0.04251814008937031,-1.3382236759146413,1.6810819528887375,-1.6638307458351758,1.642099754238008,1.3453287954480204,1.7320508075688772,0.20367385095098803,1.6391655207076974,1.346327876377583,1.7181111160876954,0.2035436128203986
4,2,-1.4758365530280975,-0.5096837535891638,-0.7569784232306012,0.15885821191391142,-0.5600567809614577,-0.811374211823694,-0.5773502691896257,-0.6836939128166968,-0.576277570082306,-0.8122751455709035,-0.4594948333722908,-0.6848056274276478

In [6]:
X = stroke.drop("stroke", axis=1)

prediction = stroke_model.predict(X)

probability = stroke_model.predict_proba(X)

In [7]:
stroke["clinical_prediction"] = prediction

stroke["clinical_probability"] = probability[:,1]

In [8]:
stroke.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,clinical_prediction,clinical_probability
0,9046,1,67.0,0,1,1,2,1,228.69,36.6,1,1,1,0.705
1,51676,0,61.0,0,0,1,3,0,202.21,28.1,2,1,1,0.655
2,31112,1,80.0,0,1,1,2,0,105.92,32.5,2,1,1,0.645
3,60182,0,49.0,0,0,1,2,1,171.23,34.4,3,1,1,0.680
4,1665,0,79.0,1,0,1,3,0,174.12,24.0,2,1,1,0.690

In [9]:
keystroke["typing_score"] = (
    keystroke.mean(axis=1, numeric_only=True)
)

In [10]:
keystroke.head()

,Unnamed: 0,H,H.1,H.2,H.3,UD,UD.1,UD.2,UD.3,DD,DD.1,DD.2,DD.3,typing_score
0,NaN,mean,std,min,max,mean,std,min,max,mean,std,min,max,NaN
1,subject,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0.08701730821492953,0.5761039407537828,-0.16712510642753534,0.5601842209595819,-0.9907082116046596,-1.1004065245125598,-0.5773502691896257,-1.0591954890137418,-0.9876101512567117,-1.0991934692759213,-0.47947286960586866,-1.058177039901876,NaN
3,1,0.04251814008937031,-1.3382236759146413,1.6810819528887375,-1.6638307458351758,1.642099754238008,1.3453287954480204,1.7320508075688772,0.20367385095098803,1.6391655207076974,1.346327876377583,1.7181111160876954,0.2035436128203986,NaN
4,2,-1.4758365530280975,-0.5096837535891638,-0.7569784232306012,0.15885821191391142,-0.5600567809614577,-0.811374211823694,-0.5773502691896257,-0.6836939128166968,-0.576277570082306,-0.8122751455709035,-0.4594948333722908,-0.6848056274276478,NaN

In [11]:
stroke.to_csv(
    r"C:\Users\navee\PreStrokeNet\Datasets\Processed\clinical_predictions.csv",
    index=False
)

keystroke.to_csv(
    r"C:\Users\navee\PreStrokeNet\Datasets\Processed\keystroke_scores.csv",
    index=False
)